### ISSUE TITLE
Nested Vizy components in tabbed views are hidden

### ISSUE THREAD

**Issue by gopeter** [verbb/vizy#158]
**Description & steps to reproduce**

I've created a Vizy field with 3 tabs like this:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/1242960/175980809-ac2521d8-0343-45df-b29f-d162574f25c6.png">

Each of the tabs holds a nested Vizy field which looks like this:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/1242960/175981443-0b167c54-cd63-427a-8a08-f8b05b1c7ed9.png">

But when I switch the tabs, the fields in the nested Vizy field disappear (they get a .hidden CSS class):

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/1242960/175981600-9abcec0a-20e5-4ca6-b154-1dc974aa6f69.png">

**Additional info**
- Plugin version: 1.0.15
- Craft version: Craft Pro 3.7.45.2
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
I think this should be fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.15",
  "...": "..."
}
```

Then run `composer update`.

**Comment by FransvdWijst** [comment]
We also encounterd problems with Nested Vizy components.

When saving an entry with nested vizy components, the nested vizy component was saved without any content. 
When saving again with content it saves correctly. This only occurs on the first save of a new nested vizy component.

Although our isseu is a bit diffrent then the original isseu. I came accross this post and decided to test the fix for the next release. It looks like this fix also works here!

**Comment by engram-design** [comment]
Fixed in [1.0.16](https://github.com/verbb/vizy/releases/tag/1.0.16)

**Comment by gopeter** [comment]
Thanks a lot! :)

**Comment by gopeter** [comment]
Hi. Unfortunately the issue isn't gone. The `hidden` class still doesn't get removed when switching tabs:

![image](https://user-images.githubusercontent.com/1242960/190649833-0ac559bb-4ad6-4c52-9276-0921acc2cc34.png)

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by gopeter** [comment]
Perfect, works fine!
