### ISSUE TITLE
Valid Unicode characters are filtered out

### ISSUE THREAD

**Issue by tom-bywild** [verbb/vizy#202]
### Describe the bug

When using text with special Unicode characters, like the `“ (U+201C) Left Double Quotation`, this character gets filtered out sometime after providing the input.

I report this as a bug, as such characters are valid and actually required by our clients to be usable.

I noticed two regex-replace used in the functions `generateHandle` and `generateKebab` in the `string.js` file, but I'm not sure they're actually the cause.

### Steps to reproduce

1. Create an empty vizy document
2. Provide a text with e.g. the left double quotation: `“This is a quote“`
3. The input stays the same, but when querying for the content, the symbol is gone

The symbol also vanishes when reloading the draft.

### Craft CMS version

Craft Pro 4.4.5

### Plugin version

2.0.12

### Multi-site?

No

**Comment by engram-design** [comment]
I can't seem to replicate this one, sorry. There's been similar reports in the past of things, and we _do_ do some encoding, but valid HTML entities like this should be fine.

The editor (after saving):

<img width="183" alt="image" src="https://user-images.githubusercontent.com/1221575/229955083-527eac43-d885-49cb-8f33-927e913226bb.png">

And the front-end:

<img width="209" alt="image" src="https://user-images.githubusercontent.com/1221575/229955100-a4af8680-e533-4938-970c-30595f299c0d.png">
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1221575/229955142-6e9a0272-6d5a-4d35-90fe-174613a65bde.png">
<img width="276" alt="image" src="https://user-images.githubusercontent.com/1221575/229955188-33780e75-00c9-4bbf-8ffd-b998160b10f1.png">

Can you confirm the above on your end? You'll notice that you can see the raw HTML entities when you view the source of the page (not just inspecting the elements on the page).

**Comment by tom-bywild** [comment]
Yes, it's showing up. But once I save or reload the page, all content is kept except the quote.

Please note that I also checked for invisible characters, so it's not a font issue. When using the PHP-API to read the nodes, the quote is missing as well, without any empty space as a leftover (or something similar). 


<img width="525" alt="Screenshot 2023-04-05 at 08 59 48" src="https://user-images.githubusercontent.com/102795185/230004938-2546db17-bd43-469f-a3d9-ca6b97f04cb9.png">

---

Edit: This is reproducible on my local machine as well as on the production & staging instance. This behaviour happens only with the Vizy-block, other text inputs (like title) keep all characters.

**Comment by engram-design** [comment]
Are you able to double check the raw value saves to the `content` table for that entry? For example, mine shows:

```json
[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"&ldquo;This is a quote&ldquo;"}]}]
```

**Comment by tom-bywild** [comment]
It's not in the DB, as far as I can tell.

```json
"html": "<p>A broken quote</p>",
"content": "[{\"type\":\"text\",\"text\":\"A broken quote\"}]",
```

```json
"html": "<p>\"A valid quote\"</p>",
"content": "[{\"type\":\"text\",\"text\":\"\\\"A valid quote\\\"\"}]",
```

| Description | Image |
| --- | --- |
<img width="1091" alt="Screenshot 2023-04-05 at 13 56 27" src="https://user-images.githubusercontent.com/102795185/230073293-207a896a-d12f-4514-8441-3872696808da.png"> | Result from Graph query |
| <img width="387" alt="Screenshot 2023-04-05 at 13 59 47" src="https://user-images.githubusercontent.com/102795185/230074034-912a3c74-1624-4818-8872-290b8ddc25d1.png"> | Screenshot of editor |

**Comment by tom-bywild** [comment]
I now wrote a JS-hack that replaces those disappearing characters in the editor's HTML input field on any input change. This was also quite tricky, and I hope we can resolve this soon. But it was the only working mitigation I saw. This way, Vizy never receives those characters in the first place, so it's "working" from an editor's POV.

If you need access to my machine, I'm happy to schedule a call for this issue. It's one of a series of issues we had with the Vizy-plugin in the past, and it's quite severe.

**Comment by tom-bywild** [comment]
For context, https://github.com/verbb/vizy/issues/198 is related to the same project.

**Comment by engram-design** [comment]
Wondering if it’s at all possible to gain a copy of your database just in case there’s something unique about that compared go my install? Totally understand if you’re unable to provide it, but if you are you can send to `support@verbb.io`. I certainly want to get to the bottom of this for you.

and sorry that you’ve had so many issues as per https://github.com/verbb/vizy/issues/198 but replicating the results you’re seeing seem to be the most difficult part here!

**Comment by tom-bywild** [comment]
@engram-design Having you take a look at the DB would be 💯 Before I can send you the data, I need you to sign an NDA, which I will send to your support.

Thanks again for your service, looking forward to resolving this issue soon.

**Comment by engram-design** [comment]
No problem and thanks, I’ll get that sorted.

**Comment by engram-design** [comment]
Looks like this was similar to https://github.com/verbb/hyper/issues/48 introduced in Craft 4.4 due to the changed LitEmoji library stripping out more than just emoji's (was also stripping out some Unicode characters like special quotes and characters).

Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.0.12"`

**Comment by tom-bywild** [comment]
Many thanks!

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)

**Comment by jeffaglenn** [comment]
We're still experiencing issues regarding special characters being deleted even after updating to the latest version (2.1.7).

We updated the plugin on 7/12 and the client fixed an entry that was affected before the update. Then a week later that same entry was saved again and apostrophes disappeared again. We're having trouble reproducing the issue but we can see it happening within the Revisions of the entry. 

Is there anything else we can do to help narrow this down?

**Comment by engram-design** [comment]
Hmmm, I can't seem to reproduce this either. Checking the revisions of my entry, it's all looking ok to me. What sort of characters are you using?

**Comment by jeffaglenn** [comment]
The only ones noticed so far are apostrophes. I know it's nothing to go off of but here are screenshots of 2 consecutive revisions happening weeks after the plugin was updated. The entry has currently been corrected again. 🤞🏻

![42](https://github.com/verbb/vizy/assets/34280463/6cf733ce-7138-4af5-8a99-e52abc0a2cea)
![43](https://github.com/verbb/vizy/assets/34280463/7c88fae4-ec6e-458a-9c5a-459a0d45e246)

**Comment by engram-design** [comment]
Thanks for the clarification. So it's seemingly happening at random? As in, you can go into an entry and correct it, and it saves all okay? Will continue to look into it.
