### ISSUE TITLE
Unable to select UL in the editor (js errors)

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#205]
### Describe the bug

I have a <ul> in my editor but when I try to select it, I get these errors:

```
caught Error: Called contentMatchAt on a node with invalid content
```
 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/5801781/232735699-751c2387-042c-43de-807b-ad598149736a.png">

Creating a new UL and saving it gives me the same results

### Steps to reproduce

1. Install latest version of Vizy
2. Create UL with a couple of list items
3. Save the entry
4. Try to select the text.

### Craft CMS version

4.4.7.1

### Plugin version

2.1.0

### Multi-site?

"Yes"

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.0"`. Do note however that because the content was saved incorrectly, it may need to be removed and re-typed.

**Comment by engram-design** [comment]
Fixed in [2.1.1](https://github.com/verbb/vizy/releases/tag/2.1.1)

**Comment by jan-dh** [comment]
@engram-design this bug is back again in Vizy 2.1.8:

<img width="627" alt="image" src="https://github.com/verbb/vizy/assets/5801781/1c08833d-5923-48f2-bad8-99aa763f9053">

**Comment by engram-design** [comment]
I mentioned you'll need to remove any list items that had this incorrect format due to the original issue. But I've also added an automatic normalization fix for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.8"`

**Comment by engram-design** [comment]
Fixed in [2.1.9](https://github.com/verbb/vizy/releases/tag/2.1.9)
