### ISSUE TITLE
Nested UL and OL not being rendered

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#209]
### Describe the bug

When creating content like this:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/5801781/233008711-1b399b76-6e4f-4cc7-8164-611b8869cd0e.png">
only the first level gets rendered

<img width="426" alt="image" src="https://user-images.githubusercontent.com/5801781/233008780-425bb152-63b2-4552-9673-9753cc5db16a.png">

### Steps to reproduce

1. Create a vizy field
2. Add multi level `ol` and `ul` elements 

### Craft CMS version

4.4.7.1

### Plugin version

2.1.1

### Multi-site?

"Yes"

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.1"`

**Comment by matthewbeta** [comment]
Hey, 

We've updated to 2.1.1 and still seeing this issue. I've tried deleting the list, saving, then re-adding and no dice.

Craft v4.4.71, Vizy v2.1.1

**Comment by engram-design** [comment]
Strange, that does seem to be working for me, with a heap of different combinations. This is me replicating your structure just to test.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/1221575/233491349-ec5ef758-e2b9-4a8e-8c68-832d444b5dd7.png">

<img width="631" alt="image" src="https://user-images.githubusercontent.com/1221575/233491368-e79b6bae-3bf0-4cc6-87bc-a2db3d9afbe4.png">

What's the method you're using to render your field? Simple, or looping through nodes?

**Comment by engram-design** [comment]
Applied in [2.1.3](https://github.com/verbb/vizy/releases/tag/2.1.3), but let me know if this is still an issue
