### ISSUE TITLE
Hyper field inside Vizy block gets cleared on save

### ISSUE THREAD

**Issue by barnslig** [verbb/vizy#252]
### Describe the bug

There seems to be a bug when using a [Hyper](https://github.com/verbb/hyper) field in a Vizy Block: When modifying a paragraph in the same Vizy field, the Hyper field values get cleared on save.

The issue might be related to #224 .

This attached video shows the bug:

https://github.com/verbb/vizy/assets/734101/e5380fdb-fc8a-498e-b10e-f4db41eac319

### Steps to reproduce

1. Add a block inside a Vizy field that contains a Hyper field.
2. Set the link field values and save the entry. The Hyper field values should still be there after reload, as expected.
3. Add a paragraph to the Vizy field and save the entry, without touching the block containing a Hyper field.
4. The Hyper field values are now cleared.

### Craft CMS version

Craft Pro 4.5.3

### Plugin version

2.1.8

### Multi-site?

No

### Additional context

[Hyper Plugin](https://github.com/verbb/hyper) Version: 1.1.11

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.8"`

**Comment by engram-design** [comment]
Fixed in [2.1.9](https://github.com/verbb/vizy/releases/tag/2.1.9)

**Comment by barnslig** [comment]
Hello @engram-design,

Unfortunately, the bug is still occuring with the following configurations:

* Craft Pro 4.5.3, Vizy 2.1.9, Hyper 1.1.11
* Craft Pro 4.5.5, Vizy 2.1.10, Hyper 1.1.13

Can you please review the bug again?

Reproducing the bug should be possible through the same steps as provided in my initial bug report, i.e. edit a paragraph beside the Hyper field, wait for draft auto-save, save the page --> Hyper field gets cleared.

Best regards!

**Comment by barnslig** [comment]
Just as a side note: The bug seems to be solved when this method gets invoked in the frontend: https://github.com/verbb/vizy/blob/5f18edba3c7af3c27737797bc0f78e0877ec8334/src/web/assets/field/src/js/components/input/VizyBlockFields.vue#L84

**Comment by engram-design** [comment]
I can't seem to replicate that with your exact steps, sorry. I might suggest getting onto Craft 4.5.6.1 as there's been a few JS-related issues with Hyper and Vizy caused by some changes with Craft.

> when this method gets invoked in the frontend

What did you mean by this?

**Comment by barnslig** [comment]
I created a fresh install with Craft 4.5.6.1, Hyper 1.1.13, Vizy 2.1.10, added a new Vizy field with a block containing a Hyper field, and could reproduce the issue in Chrome 117.0.5938.88 as you can see in this video:

https://github.com/verbb/vizy/assets/734101/431ee751-9ee1-4889-8f36-6e0859e18aa7

Let me know if you need a project config dump to reproduce the issue!

My second comment was related to the frontend JavaScript interaction of Vizy + Hyper. If you execute the following line of code in the browser developer tools console while being on the admin page that you can see in my video, the problem no longer occures:

```javascript
document.querySelectorAll('.hyper-input-component').forEach(x =>x.setAttribute('x-touched', '1'));
```

The line should trigger the MutationObserver inside [VizyBlockFields.vue](https://github.com/verbb/vizy/blob/5f18edba3c7af3c27737797bc0f78e0877ec8334/src/web/assets/field/src/js/components/input/VizyBlockFields.vue#L55), which in turn calls the `emitUpdate` function.

**Comment by engram-design** [comment]
Oh gotcha, I see what you're saying. Hmm, in that case, there might be some form of race condition or delay in registering a change to the field contents, which means that the `MutationObserver` isn't triggering there is an update for the block, which is how Vizy Block fields are serialized to be saved.

Here's my reproduction

https://github.com/verbb/vizy/assets/1221575/e439bb2c-8dc7-412e-a39d-33fa84221c6d

If you can send your entire new project to `support@verbb.io` that'd be very handy getting your reproduction up quickly.

**Comment by engram-design** [comment]
Thanks for that, I'm not sure _why_ I wasn't able to replicate it on my install, but a fresh one did the trick. 

Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.10"`

**Comment by engram-design** [comment]
Fixed in [2.1.11](https://github.com/verbb/vizy/releases/tag/2.1.11)
