### ISSUE TITLE
Text field content wiped out on first save to create the entry

### ISSUE THREAD

**Issue by Stepho288** [verbb/vizy#323]
### Describe the bug

When creating a new module that has a Vizy text field, the content of that particular field gets erased after the first save to create the entry. 

https://www.loom.com/share/e3a371551cd44ffb8d705ac44e64435b?sid=07761dc3-4cd5-4311-aa37-88c87a5c8fe5

### Steps to reproduce

1. Create a new entry in the module section - [Screenshot](https://shft.cl/4js8f7ys)
2. Choose the Text-Media entry type - [Screenshot](https://shft.cl/4x4827mc)
3. Add content in the Text field (handle: `simpleRichText`) - [VIEW FIELD SETTINGS](https://shft.cl/6bt4f7mw)
4. Click on "Create Entry" - [Screenshot](https://shft.cl/wq5027w6)

### Craft CMS version

5.4.9

### Plugin version

3.0.4

### Multi-site?

Yes

### Additional context

We're also using the Hyper plugin for the [button field](https://shft.cl/wr1rgr7e9) in this entry type's data-model.

**Comment by engram-design** [comment]
I have a feeling this might indeed be an issue between Hyper and Vizy, which I _believe_ is fixed in Hyper 2.1.0 and Craft 5.5. But let me know if that's not the case!

**Comment by Stepho288** [comment]
Hi @engram-design ! Thanks for the reply :) 

We updated our Craft to 5.5.0.1, Hyper to 2.2.0 and Vizy to 3.0.5 and I still have the exact same issue on my first try. The content of the Vizy field gets wiped out on first save to create the entry.

**Comment by bleepsandblops** [comment]
We're having a very similar issue on entry creation except that what is wiped out is Entries, Assets and CKEditor content within blocks, EXCEPT for the last block. There is no Hyper field on the entry or in the blocks (but it is installed on the site and used in other blocks). (This is on craft 5.4.10.1 / vizy 3.0.4 / hyper 2.0.5  - will update now)

EDIT: the last block wasn't correct (client had started filling back in), it wipes all of them.

**Comment by Stepho288** [comment]
Hello @engram-design !

Just checking if you have any updates on this? We're still experiencing the same exact issue on our end and our clients are starting to notice it during their content entry and are asking about it.

For context, we updated Craft to 5.5.4, Vizy to 3.0.5 and Hyper to 2.2.1.

Let me know if there's something I can do to help.

Thank you!!

**Comment by engram-design** [comment]
Still struggling to reproduce this one, sorry. I did replicate your field setup exactly as well.

One question, in your video I noticed that after typing in the "CMS Identifier" field, the Hyper field shows a change. Does this still happen with Hyper 2.2.1? The reason I ask is that this could be related to how we use the element editor serializer under the hood, so gives me a good direction to pursue.

**Comment by engram-design** [comment]
In related news, I am in the middle of some refactoring to improve this behaviour, generally. I'd be keen to see if the latest changes I've been making improve your situation.

To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.5"`.

**Comment by Stepho288** [comment]
Hi @engram-design ! Thank you for your fast reply. 

Regarding your first message, it seems that the behaviour you're describing doesn't happen with Hyper 2.2.1. Here's a **[screenshot](https://shft.cl/482s0i75m)** of the filled fields before saving. I didn't enter anything in the Hyper field to show you that it's one of the only fields that doesn't show changes.

As for the second message, I will ask the dev team to run the command and I'll get back to you with feedback. Thank you so much for letting us try this ahead!

**Comment by Stepho288** [comment]
Hi @engram-design

So, the dev team just ran `composer require verbb/vizy:"dev-craft-5 as 3.0.5"` as you suggested, but unfortunaltely it didn't do anything. The bug is still happening. We'll be awaiting further instructions to test something else. Thank you!

**Comment by engram-design** [comment]
Thanks for confirming it's not working. I'm wondering if you might be able to reduce your fields as much as you can while still replicating this? I'd probably recommend creating a new entry type, so as not to mess with your existing content.

Still trying to replicate this with a (seemingly) identical field setup to what I can see in your video/screenshot.

**Comment by nitriques** [comment]
Hi @engram-design 
We have this problem on more than a single instance. (I work with @Stepho288 )
Seems like we are still having it

**Comment by engram-design** [comment]
@nitriques As I mentioned, can you reduce your fields as much as you can to replicate it in an exact scenario? While @Stepho288 video is excellent, there's a lot of factors at play with different fields, Hyper, and maybe more fields I can't see in the video.

Is this something you can replicate with just the Title and Vizy for example, or does it also need Hyper there as well?

**Comment by engram-design** [comment]
Should be fixed in [3.1.0](https://github.com/verbb/vizy/releases/tag/3.1.0).
