### ISSUE TITLE
HTML character encoding issue for &ldquo; when upgrading

### ISSUE THREAD

**Issue by portedison** [verbb/vizy#324]
### Describe the bug

Similar issue : https://github.com/verbb/vizy/issues/115

When upgrading from **Vizy 1.0.23 and Craft CMS 3.9.10**, to **Vizy 2.1.23 and Craft CMS 4.13.1.1**

Character were previously stored in the database as `&ldquo;` any newly created content saves in the database as `“` though on an upgrade none of these characters have been migrated. When inspecting the code in the editors html view they appear as `&amp;ldquo;` - though in the database they are still stored as `&ldquo;`. A manual update fixes these.

Are there any recommended steps to migrate these?

<img width="220" alt="Screenshot 2024-11-26 at 4 35 26 PM" src="https://github.com/user-attachments/assets/866cfa01-138a-4315-870a-864c2612de8f">
<img width="238" alt="Screenshot 2024-11-26 at 4 35 34 PM" src="https://github.com/user-attachments/assets/71cd700c-1f95-43b5-925e-6d0f74671799">

### Steps to reproduce

1. Create a project with Vizy 1.0.23 and Craft CMS 3.9.10
2. Create some content with a `&ldquo;` in a Vizy Field.
3. Migrate to Vizy 2.1.23 and Craft CMS 4.13.1.1

### Craft CMS version

3.9.10 -> 4.13.1.1

### Plugin version

1.0.23 -> 2.1.23

### Multi-site?

No

### Additional context

We have written a migration to update each entry in the database, though we've come across an issue where SuperTable content inside Vizy field, is difficult to access/update. (I'll mention that in another ticket and attach).

**Comment by engram-design** [comment]
Sounds like this'll be encoding changes. Just to be clear, re-saving the entry doesn't change anything, but re-typing the encoded values (swapping `&amp;` for `&` for example) works correctly?

I might have to provide a manual console command to run on field content to take care of this.

In addition, there's actually an internal helper function to help with updating content, which handles global, Matrix and Super Table content. We use this in [Hyper](https://github.com/verbb/hyper/blob/1151c7f61a4784f8b2c5f7bfda8102269442c6ee/src/migrations/PluginMigration.php#L129-L155) migrations.

**Comment by portedison** [comment]
_Sounds like this'll be encoding changes. Just to be clear, re-saving the entry doesn't change anything, but re-typing the encoded values (swapping &amp; for & for example) works correctly?_

Yes that is correct. 

That command could be helpful, the other issue we had was where we have the structure - 
`pageBlocks(Neo) > richText(Neo : Common Block) > blockRichText (Vizy) > vizy2ColumnsTable (Super Table)`

But the last one `vizy2ColumnsTable` 'disappears', though it still appears to be in the database in the old craft format. I can make a ticket explaining more about that if it's useful? There is a comment relating to this already https://github.com/verbb/vizy/issues/292#issuecomment-2268766550

**Comment by Kethatril** [comment]
This is the change that surfaced the issue: https://github.com/verbb/vizy/commit/819a013d577925488e6f565e3ac1d02edf544dc0

In 2.1.22 the characters showed up correctly in the editor and if you modified the field and saved it the database values would no longer have the escaped characters and that field would show up correctly in 2.1.23 in the editor. But because it only gets fixed by code in the editor resaving all entries using the cli doesn't fix the issue.

**Comment by engram-design** [comment]
Thanks for pointing that out @Kethatril that's a good start.

**Comment by rungta** [comment]
@engram-design We’ve noticed a similar issue. After we upgraded Vizy from 2.1.20 to 2.1.23, all HTML entities present in the content have started showing up as text in the control panel. Re-saving the entry (in the CP or via the CLI) does not appear to fix the issue either.

We are currently on Vizy 2.1.25 (Craft 4.14.11.1) but the issue persists. I went back a couple versions and was able to successfully isolate entities becoming visible in the editor to the point where we upgraded to Vizy 2.1.23.

Here is an example:

```json
[{"type":"paragraph","attrs":[],"content":[{"type":"text","text":"We are an international development firm specializing in four pivotal domains that collectively aim to promote prosperity and resilience, specifically in "},{"type":"text","marks":[{"type":"textStyle"}],"text":"underdeveloped, fragile, and conflict-affected contexts"},{"type":"text","text":". Our expertise spans Research and Analysis, Monitoring, Evaluation, and Learning, Institutional Strengthening, and Social and Behavior Change&nbsp;Communication.&nbsp;"}]}]
```

![Image](https://github.com/user-attachments/assets/9d5d12d8-ff21-4d0a-8127-fc65576c9387)

This is troublesome for two reasons:
1. HTML entities are being rendered as text, leading to authors encountering “corrupted” content that they don't quite understand.
2. Authors are now able to write un-escaped markup inside a Vizy field, including HTML tags and entities.

Any suggestions on how to resolve this?

**Comment by engram-design** [comment]
If you remove those `&nbsp;` texts, do they come back? Was the text pasted from somewhere like Word?

I've got a fairly comprehensive list of entities that when entered into the field are rendering correctly.

While I can see the characters with your content, that would make sense as it's the literal `&nbsp;` text present.

You've always been able to write markup in Vizy fields, but we certainly protect against anything malicious making its way in there. This is commonly for when you _want_ to write code in the editor content.

**Comment by bartdigitalpulse** [comment]
We're seeing this issue as wel. Upgraded from craft 3 to 4 (latest). All the French text from the Globals has faulty encoding:

Original Craft 3:
`De la fraîcheur à l'intérieur et de l'ombre. Les systèmes de protection solaire, créer une maison agréable.`

Craft 4:
`De la fra&icirc;cheur &agrave; l'int&eacute;rieur et de l'ombre. Les syst&egrave;mes de protection solaire, cr&eacute;er une maison agr&eacute;able.`

Edit: this is a vizy field inside a supertable field

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.25"`.

You can also safely apply this on your already Craft 4 upgraded site. In Vizy 1, we stored the encoded value of HTML entities, and in Vizy 2, we don't encode them - causing this issue. The migration that will run upon upgrade will convert these for you, as well as sanitize any potentially malicious content correctly and better than in Vizy 1.

**Comment by BenPicard** [comment]
> Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.25"`.
> 
> You can also safely apply this on your already Craft 4 upgraded site. In Vizy 1, we stored the encoded value of HTML entities, and in Vizy 2, we don't encode them - causing this issue. The migration that will run upon upgrade will convert these for you, as well as sanitize any potentially malicious content correctly and better than in Vizy 1.

@engram-design

I still have the bug even with this dev update

It fixed my save error but now all my contents have html tag in them

https://l.picard.ca/erxHV
https://l.picard.ca/0iTay

**Comment by BenPicard** [comment]
@engram-design just to add to that

front-end before update: https://l.picard.ca/ijOXJ
back-end before update: https://l.picard.ca/IzdO2

front-end after update: https://l.picard.ca/aUOMo
back-end after update: https://l.picard.ca/cY3F6

I restore our website to the old version of vizy, we can't save update on the page but at least the front-end is not broken.

**Comment by engram-design** [comment]
Right, so you have a CKEditor field _inside_ the Vizy field content, that complicates things considerably.

Just pushed another fix to address this properly. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.25"`.

**Comment by engram-design** [comment]
Updated in [2.1.26](https://github.com/verbb/vizy/releases/tag/2.1.26).

**Comment by tomkiss** [comment]
I've got this issue too. 

It's happened before, a while ago now, and I managed to catch it. 

But now I don't quite know when it's happened and I don't have a backup to revert to, thats from a previous version with the database in a good state. Reverting to previous versions of an entry with the issue makes no difference.

It's mostly `rsquo;` and `lsquo;` appearing throughout the text, `&amp;rsquo;` in source.

Not sure when it occurred but it's on Craft 5.8.21 with Vizy 3.0.13.
(Just updated to 3.1.2, with no difference).

Previous updates were, it was likely one of these:
 - 3.0.12
 - 3.0.11
 - 3.0.8

Is there any way to recover from this? 
I've around 64 entries across a large internal handbook, welp. Annoyingly "rsquo" doesn't appear in entries search so I can't search for articles with the issue.

Config is:

<img width="1126" height="87" alt="Image" src="https://github.com/user-attachments/assets/2419c7cf-b1df-4a80-b41b-6fda2d8ef95e" />


```json
{
  "buttons": [
    "html",
    "formatting",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "subscript",
    "superscript",
    "ordered-list",
    "unordered-list",
    "code",
    "hr",
    "highlight",
    "clear-format",
    "table",
    "image",
    "link",
    "undo",
    "redo"
  ],
  "formatting": ["paragraph", "h2", "h3", "h4", "blockquote", "code-block"],
  "table": [
    "insert-table",
    "delete-table",
    "add-col-before",
    "add-col-after",
    "delete-col",
    "add-row-before",
    "add-row-after",
    "delete-row",
    "merge-cells",
    "split-cells",
    "toggle-header-column",
    "toggle-header-row",
    "toggle-header-cell"
  ],
  "toolbarFixed": true
}
```

**Comment by tomkiss** [comment]
....have manually edited all the affected entries now. Will keep an eye out for if it happens again!

**Comment by engram-design** [comment]
Sorry about that @tomkiss if it makes any difference, we don't touch your content at all anymore, so if anything happens, it's really going to be down to the renderer and your content remains safe.

**Comment by tomkiss** [comment]
@engram-design No worries - I can't be too sure about when this happened. It could have been (must have been?) a while ago,  pre-bug fix. Anyway, sorted now - thanks for replying nonetheless!

**Comment by KevinBodi** [comment]
@engram-design We've had this issue too. It seems that way back some upgrade perhaps caused content to have character encoding issues in the control panel. Prior to [version 3.0.13 (Improve content-encoding handling for special-characters, HTML content, emoji’s and more)](https://github.com/verbb/vizy/commit/b2c89a916459800d56b4f3827bc9fbd5d882d613) the content that rendered in frontend still looked good while content in the control panel had issues. After version 3.0.13 and beyond, content in the frontend also renders with the character encoding issues visible.

Control panel before **and** after 3.0.13:
<img width="804" height="253" alt="Image" src="https://github.com/user-attachments/assets/9aba80c2-d68c-44d0-99b9-5463f484a959" />

Frontend before 3.0.13 (3.0.12):
<img width="658" height="320" alt="Image" src="https://github.com/user-attachments/assets/2510381d-fdd8-4d7d-9265-5d2eadc2d38d" />

Frontend after 3.0.13:
<img width="647" height="426" alt="Image" src="https://github.com/user-attachments/assets/8daeae35-8ff2-4ae0-9cfd-828baca685bf" />



We solved this with a custom Twig filter that we use on content from `node.renderHtml()` and similar
```php
<?php
namespace modules;

use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;

class HtmlDecodeTwigExtension extends AbstractExtension
{
    public function getFilters(): array
    {
        return [
            new TwigFilter('html_decode', [$this, 'htmlDecode'], ['is_safe' => ['html']]),
        ];
    }

    public function htmlDecode(string $value): string
    {
        return html_entity_decode($value, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    }
}
```
